name: Feature Request
description: Suggest an idea to improve Lemon Packet
title: "[Feature] "
labels: ["feature", "status:triage"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem are you trying to solve?
      placeholder: Tell us why this feature is useful.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature in detail.
      placeholder: Explain expected behavior and user experience.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workaround or alternative you already tried?

  - type: textarea
    id: other-information
    attributes:
      label: Other information
      description: Links, screenshots, or related mods/issues.
