name: Question
description: Ask a question about usage or behavior
title: "[Question] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: |
        Ask your question here.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide version, launcher, and related details so we can answer accurately.
      placeholder: Lemon Packet 1.0.0, Minecraft 1.21.10, Prism Launcher 9.2
